version: "2"
networks:
  galactusnet:
    driver: bridge

services:
  postgres_host:
    image: postgres
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - galactusnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  room:
    image: rjected/galactusroom
    expose:
      - "8080"
    restart: always
    networks:
      - galactusnet
    depends_on:
      postgres_host:
        condition: service_healthy

  web:
    image: rjected/galactusweb
    expose:
      - "3000"
    depends_on:
      - room
    restart: always
    networks:
      - galactusnet

  reverseproxy:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - web
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - galactusnet

