version: "3"
networks:
  galactusnet:
    driver: bridge

services:
  room:
    image: rjected/galactusroom
    expose:
        - "8080"
    restart: always
    networks:
        - galactusnet

  web:
    image: rjected/galactusweb
    expose:
        - "3000"
    depends_on:
      - room
    restart: always
    networks:
        - galactusnet

  reverseproxy:
    image: nginx:latest
    ports:
        - 80:80
    depends_on:
        - web
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
        - galactusnet

