version: "3"
services:
  reverseproxy:
    image: rjected/galactusnginx
    ports:
      - 80:80
    restart: always

  room:
    image: rjected/galactusroom
    depends_on:
      - reverseproxy
    restart: always

  web:
    image: rjected/galactusweb
    depends_on:
      - reverseproxy
    restart: always
