apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: room
  name: room
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: room
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: room
    spec:
      containers:
      - image: rjected/galactusroom
        imagePullPolicy: ""
        name: room
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
