/* tslint:disable */
/* eslint-disable */
/**
 * queueservice
 * Video queue service
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sbirudavolu@umass.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    VideoQueue,
    VideoQueueFromJSON,
    VideoQueueToJSON,
} from '../models';

export interface GetQueueRequest {
    code: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Returns the queue
     */
    async getQueueRaw(requestParameters: GetQueueRequest): Promise<runtime.ApiResponse<VideoQueue>> {
        if (requestParameters.code === null || requestParameters.code === undefined) {
            throw new runtime.RequiredError('code','Required parameter requestParameters.code was null or undefined when calling getQueue.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/queue/{code}`.replace(`{${"code"}}`, encodeURIComponent(String(requestParameters.code))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoQueueFromJSON(jsonValue));
    }

    /**
     * Returns the queue
     */
    async getQueue(requestParameters: GetQueueRequest): Promise<VideoQueue> {
        const response = await this.getQueueRaw(requestParameters);
        return await response.value();
    }

}
