/* tslint:disable */
/* eslint-disable */
/**
 * queueservice
 * Video queue service
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sbirudavolu@umass.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Video request
 * @export
 * @interface AddVideo
 */
export interface AddVideo {
    /**
     * 
     * @type {string}
     * @memberof AddVideo
     */
    url?: string;
}

export function AddVideoFromJSON(json: any): AddVideo {
    return AddVideoFromJSONTyped(json, false);
}

export function AddVideoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddVideo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function AddVideoToJSON(value?: AddVideo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
    };
}


