/* tslint:disable */
/* eslint-disable */
/**
 * queueservice
 * Video queue service
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sbirudavolu@umass.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Play video request, moves video to top of queue
 * @export
 * @interface PlayVideo
 */
export interface PlayVideo {
    /**
     * 
     * @type {string}
     * @memberof PlayVideo
     */
    id?: string;
}

export function PlayVideoFromJSON(json: any): PlayVideo {
    return PlayVideoFromJSONTyped(json, false);
}

export function PlayVideoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayVideo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function PlayVideoToJSON(value?: PlayVideo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


