/* tslint:disable */
/* eslint-disable */
/**
 * queueservice
 * Video queue service
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sbirudavolu@umass.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Remove video reponse and request
 * @export
 * @interface RemoveVideo
 */
export interface RemoveVideo {
    /**
     * 
     * @type {string}
     * @memberof RemoveVideo
     */
    id?: string;
}

export function RemoveVideoFromJSON(json: any): RemoveVideo {
    return RemoveVideoFromJSONTyped(json, false);
}

export function RemoveVideoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoveVideo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function RemoveVideoToJSON(value?: RemoveVideo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


