/* tslint:disable */
/* eslint-disable */
/**
 * queueservice
 * Video queue service
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: sbirudavolu@umass.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Video entry
 * @export
 * @interface Video
 */
export interface Video {
    /**
     * 
     * @type {string}
     * @memberof Video
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof Video
     */
    index?: number;
    /**
     * 
     * @type {string}
     * @memberof Video
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof Video
     */
    thumbnailUrl?: string;
    /**
     * 
     * @type {Date}
     * @memberof Video
     */
    addedAt?: Date;
}

export function VideoFromJSON(json: any): Video {
    return VideoFromJSONTyped(json, false);
}

export function VideoFromJSONTyped(json: any, ignoreDiscriminator: boolean): Video {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'index': !exists(json, 'index') ? undefined : json['index'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'thumbnailUrl': !exists(json, 'thumbnailUrl') ? undefined : json['thumbnailUrl'],
        'addedAt': !exists(json, 'addedAt') ? undefined : (new Date(json['addedAt'])),
    };
}

export function VideoToJSON(value?: Video | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'index': value.index,
        'url': value.url,
        'thumbnailUrl': value.thumbnailUrl,
        'addedAt': value.addedAt === undefined ? undefined : (value.addedAt.toISOString()),
    };
}


